version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    # command: python manage.py runserver 0.0.0.0:8000 --settings=Bookpro.settings
    command: sh -c "python manage.py makemigrations && 
                    python manage.py migrate &&
                    gunicorn Bookpro.wsgi:application --bind 0.0.0.0:8000"

    container_name: bookpro_con
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - 8000:8000
    restart: always
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=rabee123
      - POSTGRES_NAME=postgres
      - POSTGRES_DB=postgres
    depends_on:
      - db
    networks:
      - books_network


  db:
    image: postgres:15
    container_name: db_con
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=rabee123
      - POSTGRES_NAME=postgres
      - POSTGRES_DB=postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5434:5432
    expose:
      - "5434"
    networks:
        - books_network


  nginx:
    image: nginx
    build: ./nginx
    container_name: nginx_con
    ports:
      - 1337:80
    volumes:  
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - web
    restart: always
    networks:
      books_network:


networks:
  books_network:
    driver: bridge


volumes:
  postgres_data:
  media_volume:
  static_volume: