# Generated by Django 4.2.7 on 2024-03-25 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='image',
            field=models.ImageField(default='default/account.png', upload_to='users'),
        ),
    ]
