# Generated by Django 4.2.7 on 2023-11-29 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='quotes',
            field=models.ManyToManyField(to='bookapp.quote'),
        ),
    ]
