# Generated by Django 4.2.7 on 2024-04-01 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0002_remove_book_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bookapp.author'),
            preserve_default=False,
        ),
    ]
