# Generated by Django 4.2.7 on 2023-11-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0003_alter_book_cover_alter_book_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], default='en', max_length=30),
        ),
        migrations.AddField(
            model_name='book',
            name='pages',
            field=models.IntegerField(default=250),
        ),
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.ImageField(default='None', null=True, upload_to='media/authors/'),
        ),
    ]
