# Generated by Django 4.2.7 on 2023-12-01 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0004_book_language_book_pages_alter_author_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.ImageField(default='None', null=True, upload_to='authors/'),
        ),
    ]
