# Generated by Django 4.2.7 on 2024-04-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0004_customuser_currently_reading_customuser_read_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='currently_reading',
            field=models.ManyToManyField(blank=True, related_name='currently_users', to='bookapp.book'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='read',
            field=models.ManyToManyField(blank=True, related_name='read_users', to='bookapp.book'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='want_to_read',
            field=models.ManyToManyField(blank=True, related_name='want_to_read_users', to='bookapp.book'),
        ),
    ]
