# Generated by Django 4.2.7 on 2024-04-12 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0006_alter_product_managers_alter_book_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='defaults/account.jpg', upload_to='users/'),
        ),
    ]
