# Generated by Django 4.2.7 on 2023-12-01 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0006_author_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='story',
            field=models.TextField(default='n', max_length=300),
        ),
    ]
