# Generated by Django 5.0.4 on 2024-06-06 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0008_post_cover_remove_book_author_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='published',
            field=models.DateField(default='1980-1-1'),
        ),
    ]
